select
   type
from
   v$controlfile_record_section
order by
   type
;
--
-- ACM OPERATION
-- ARCHIVED LOG
-- AUXILIARY DATAFILE COPY
-- BACKUP CORRUPTION
-- BACKUP DATAFILE
-- BACKUP PIECE
-- BACKUP REDOLOG
-- BACKUP SET
-- BACKUP SPFILE
-- CKPT PROGRESS
-- COPY CORRUPTION
-- DATABASE
-- DATABASE BLOCK CORRUPTION
-- DATABASE INCARNATION
-- DATAFILE
-- DATAFILE COPY
-- DATAFILE HISTORY
-- DELETED OBJECT
-- FILENAME
-- FLASHBACK LOG
-- FOREIGN ARCHIVED LOG
-- GUARANTEED RESTORE POINT
-- INSTANCE SPACE RESERVATION
-- LOG HISTORY
-- MTTR
-- MULTI INSTANCE REDO APPLY
-- OFFLINE RANGE
-- PDB RECORD
-- PDBINC RECORD
-- PROXY COPY
-- RECOVERY DESTINATION
-- REDO LOG
-- REDO THREAD
-- REMOVABLE RECOVERY FILES
-- RESTORE POINT
