select
  lower(command_name)
from
  v$sqlcommand
order by
  command_name;
-- alter assembly
-- alter cluster
-- alter database
-- alter database link
-- alter dimension
-- alter disk group
-- alter edition
-- alter flashback archive
-- alter function
-- alter index
-- alter indextype
-- alter java
-- alter library
-- alter materialized view 
-- alter materialized view log
-- alter operator
-- alter outline
-- alter package
-- alter package body
-- alter procedure
-- alter profile
-- alter resource cost
-- alter rewrite equivalence
-- alter role
-- alter rollback seg
-- alter sequence
-- alter session
-- alter summary
-- alter synonym
-- alter system
-- alter table
-- alter tablespace
-- alter tracing
-- alter trigger
-- alter type
-- alter type body
-- alter user
-- alter view
-- analyze cluster
-- analyze index
-- analyze table
-- associate statistics
-- audit object
-- call method
-- change password
-- comment
-- commit
-- create assembly
-- create bitmapfile
-- create cluster
-- create context
-- create control file
-- create database
-- create database link
-- create dimension
-- create directory
-- create disk group
-- create edition
-- create flashback archive
-- create function
-- create index
-- create indextype
-- create java
-- create library
-- create materialized view 
-- create materialized view log
-- create operator
-- create outline
-- create package
-- create package body
-- create pfile
-- create procedure
-- create profile
-- create restore point
-- create role
-- create rollback seg
-- create schema
-- create schema synonym
-- create sequence
-- create spfile
-- create summary
-- create synonym
-- create table
-- create tablespace
-- create trigger
-- create type
-- create type body
-- create user
-- create view
-- declare rewrite equivalence
-- delete
-- disassociate statistics
-- do not use 184
-- do not use 185
-- do not use 186
-- drop assembly
-- drop bitmapfile
-- drop cluster
-- drop context
-- drop database
-- drop database link
-- drop dimension
-- drop directory
-- drop disk group
-- drop edition
-- drop flashback archive
-- drop function
-- drop index
-- drop indextype
-- drop java
-- drop library
-- drop materialized view 
-- drop materialized view  log
-- drop operator
-- drop outline
-- drop package
-- drop package body
-- drop procedure
-- drop profile
-- drop restore point
-- drop rewrite equivalence
-- drop role
-- drop rollback seg
-- drop schema synonym
-- drop sequence
-- drop summary
-- drop synonym
-- drop table
-- drop tablespace
-- drop trigger
-- drop type
-- drop type body
-- drop user
-- drop view
-- explain
-- flashback database
-- flashback table
-- grant object
-- insert
-- lock table
-- noaudit object
-- no-op
-- pl/sql execute
-- purge dba recyclebin
-- purge index
-- purge table
-- purge tablespace
-- purge user recyclebin
-- rename
-- revoke object
-- rollback
-- savepoint
-- select
-- set constraints
-- set role
-- set transaction
-- truncate cluster
-- truncate table
-- undrop object
-- update
-- update indexes
-- update join index
-- upsert
-- validate index  
  
