select
   key,
   report_id,
   sql_id,
   refresh_count, first_refresh_time, last_refresh_time,
-- plsql_exec_time,
-- java_exec_time,
   sql_exec_start,
   status,
   username, -- user#
   elapsed_time,
   queuing_time,
   cpu_time,
   fetches,
   buffer_gets,
   disk_reads,
   direct_writes,
   io_interconnect_bytes,
   physical_read_requests,
   physical_read_bytes,
   physical_write_requests,
   physical_write_bytes,
   application_wait_time,
   concurrency_wait_time,
   cluster_wait_time,
   user_io_wait_time,
   module,
-- action,
-- service_name,
-- client_identifier, client_info,
   program,
   plsql_entry_object_id,
   plsql_entry_subprogram_id,
   plsql_object_id,
   plsql_subprogram_id,
   dbop_exec_id,
   dbop_name,
-- sid, session_serial#,
-- process_name,
   sql_text,
   is_full_sqltext,
   sql_exec_id,
   sql_plan_hash_value,
   sql_full_plan_hash_value,
   exact_matching_signature,
   force_matching_signature,
   sql_child_address,
   is_adaptive_plan,
   is_final_plan,
   px_is_cross_instance,
   px_maxdop,
   px_maxdop_instances,
   px_servers_requested,
   px_servers_allocated,
   px_server#,
   px_server_group,
   px_server_set,
   px_qcinst_id,
   px_qcsid,
   error_number,
   error_facility,
   error_message,
   binds_xml,
   other_xml,
   rm_last_action,
   rm_last_action_reason,
   rm_last_action_time,
   rm_consumer_group,
   con_id,
   con_name,
   ecid,
   in_dbop_name,
   in_dbop_exec_id,
   io_cell_uncompressed_bytes,
   io_cell_offload_eligible_bytes,
   io_cell_offload_returned_bytes,
   current_username   -- current_user#
from
   v$sql_monitor
where
   sid = 78
order by
   last_refresh_time desc;
